spring.application.name=gym
server.port=8081

logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.security=DEBUG

spring.datasource.url=${DATABASE_PUBLIC_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.flyway.enabled=true

jwt.secret=5b8e3f7a2d9c4e6b1a0f8d3c7e2b5a9f4d6c8e1b3a7f0d2c5e8b4a6f9d1c3e7
jwt.expiration=900000
jwt.refresh-expiration=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luizcordeirosneto@gmail.com
spring.mail.password=hejm xupa dnwr qjgc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true